# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 20:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('data_start', models.DateTimeField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
