# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todowork',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
