# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20171010_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='todowork',
            name='tapStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todowork',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
