# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20171010_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoingWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
