# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_doingwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='todowork',
            name='done',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='todowork',
            name='content',
            field=models.TextField(),
        ),
    ]
